Mission2Assignment/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission2Assignment.Models
{
    public class GradeCalcModel
    {
        [Required]
        [Range(0, 100)]

        public int assignments { get; set; }

        public int groupProjects { get; set; }

        public int quizzes { get; set; }

        public int exams { get; set; }

        public int intex { get; set; }
    }
}

Mission2Assignment/Controllers/BlahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission2Assignment.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mission2Assignment.Controllers
{
    public class BlahController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]

        public IActionResult GradeCalc()
        {
            return View();
        }

        [HttpPost]

        public IActionResult GradeCalc(GradeCalcModel model)
        {
            return View();
        }

    }
}

Mission2Assignment/Views/Blah/GradeCalc.cshtml
@{
    ViewData["Title"] = "Grade Calculator";
}

@model GradeCalcModel;

<!--A "Grade Calculator" form that takes as input a percentage scored for each grade
category listed in the syllabus-->


<br />
<form method="post">
    <h3>Grade Calculator</h3>
    <p>Insert the percentage scored for each grade category listed below. </p>
    <br />
    <label>Assignments: </label>
    <input id="assignments" type="number" asp-for="assignments" style="width:150px; text-align:center;"/>
    <br /><br />
    <label>Group Projects: </label>
    <input id="groupProjects" type="number" asp-for="groupProjects" style="width:150px; text-align:center;"/>
    <br /><br />
    <label>Quizzes: </label>
    <input id="quizzes" type="number" asp-for="quizzes" style="width:150px; text-align:center;"/>
    <br /><br />
    <label>Exams: </label>
    <input id="exams" type="number" asp-for="exams" style="width:150px; text-align:center;"/>
    <br /><br />
    <label>INTEX: </label>
    <input id="intex" type="number" asp-for="intex" style="width:150px; text-align:center;"/>
    <br /><br />
    <input id="btnGrade" type="submit" value="Calculate" name="btnGrade" style="width:150px; text-align:center;"/>
</form>
<br />

<div style="color:red;" asp-validation-summary="All"></div>

<script src="~/js/mycalc.js"></script>

Mission2Assignment/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "About Madaleine Osmun";
}

<br />
<!--Header that lists my preferred name-->
<h1>Madaleine</h1>
<br />

<!--A picture of yourself doing something you enjoy-->
<img src="img/funThings.png" style="width:50%;" />
<br />
<br />

<!--A paragraph on what you hope to get out of this IS 413 class-->
<h3>What I hope to get out of IS 413 Class: </h3>
<p>
    I hope to practice my programming skills a ton with this class and solidify the knowledge that I have already gained
    in programming by practicing it again and again. I hope to gain more confidence in programming as well since that is
    something I would like to do in my career.
</p>

<!--A list of the Top #3 jobs you are most interested in pursuing when you graduate-->
<h3>The top 3 jobs I am most interested in: </h3>
<ol>
    <li>Web Developer</li>
    <li>Software Developer</li>
    <li>Cloud Engineer/Architect</li>
</ol>

Mission2Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <!--Style the site using Bootstrap.-->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!--Include at least one change to the styling using your own CSS file-->
    <link href="~/css/mycss.css" rel="stylesheet" />

    <!--An icon for the website (displayed on the tab next to the website title)
    (#notcoveredinthevideos)-->
    <link rel="icon" type="image/png" href="~/img/favicon1.png" sizes="16x16">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>

    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
</head>
    <body class="container center-cont">

        <nav>
            <a asp-controller="Blah" asp-action="Index">Home</a>
            <a asp-controller="Blah" asp-action="GradeCalc">Grade Calculator</a>
        </nav>

        <div>
            @RenderBody()
        </div>

        <footer>Contact Madaleine Osmun with any concerns.</footer>

        <!--Style the site using Bootstrap.-->
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        
    </body>
</html>